# SEE "youtube-dl" for more details about the options
# https://github.com/ytdl-org/youtube-dl

# USAGE: youtube-dl [VIDEO_URL] --config-location youtube-dl_audio.conf

# Restrict filenames to only ASCII characters
--restrict-filenames

# Abort downloading of further videos if an error occurs
--abort-on-error

# Disable filesystem caching
--no-cache-dir
# Delete all filesystem cache files
--rm-cache-dir
# Do not use .part files - write directly into output file
--no-part

# Execute a command on the file after downloading
#--exec